### ISSUE TITLE
Make fails due to missing header files

### ISSUE THREAD

**Issue by DavidJRichards** [revk/ESP32-Simple#1]
I would like to be able to re-compile the software to use an alternative serial port definition but when I try I get compile errors in the  RevK library compile - starting with missing files esp_wifi.h and some others too.

Maybe the esp idf  version I'm using is the wrong one, the espidf example I have tried compile without error.

I'd like to be able to drive the board from a serial port (not USB).

Any help gratefully received, David.

**Comment by revk** [comment]
I am using latest stable 4.4.1 which should work.
I see there is a stable 4.4.2 so I'll look in to any changes for that shortly.

**Comment by revk** [comment]
Looks like this code is out of date, so I'm working on it.
